/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_tylercruz;

import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Tyler C
 */
public class MainExamenLab extends javax.swing.JFrame {

    /**
     * Creates new form MainExamenLab
     */
    public MainExamenLab() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_Login = new javax.swing.JDialog();
        MainPanel_Login = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JT_UserName_Login = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JT_Password_Login = new javax.swing.JTextField();
        JB_Login_Login = new javax.swing.JButton();
        JD_Registrar = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        JT_Nombre_Registrar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        JT_Apellido_Registrar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        JT_Telefono_Registrar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        JT_Usuario_Registrar = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        JT_Password_Registrar = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        JSpinner_WifiQuality_Registrar = new javax.swing.JSpinner();
        JB_Registrar = new javax.swing.JButton();
        FriendRequestMenu = new javax.swing.JPopupMenu();
        JMI_AcceptFriend = new javax.swing.JMenuItem();
        JMI_DenyFriend = new javax.swing.JMenuItem();
        MessageMenu = new javax.swing.JPopupMenu();
        JMI_SendMessage = new javax.swing.JMenuItem();
        JD_ShowMessage = new javax.swing.JDialog();
        MainPanel_ListChat = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextArea_Chat = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        SeeMessageMenu = new javax.swing.JPopupMenu();
        JMI_SeeChat = new javax.swing.JMenuItem();
        JD_Mensaje = new javax.swing.JDialog();
        MainPanel_Mensaje = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextArea_Mensaje = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        JT_Usuario_Create = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JT_Password_Create = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JSpinner_WifiQuality = new javax.swing.JSpinner();
        JB_CreateUsuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JT_Nombre_Create = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        JT_Apellido_Create = new javax.swing.JTextField();
        JT_Telefono_Create = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTree_Receptores = new javax.swing.JTree();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        JT_GroupName = new javax.swing.JTextField();
        JB_CreateGroup = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JList_Friends = new javax.swing.JList<>();
        JB_ListFriends = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        JB_SendSolicitud = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        JT_UserToSend = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        JB_ListRequests = new javax.swing.JButton();
        CB_Requests = new javax.swing.JComboBox<>();
        MainMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMI_Login = new javax.swing.JMenuItem();
        JMI_Registrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel2.setText("User Name: ");

        jLabel3.setText("Password:");

        JB_Login_Login.setText("Login");
        JB_Login_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Login_LoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanel_LoginLayout = new javax.swing.GroupLayout(MainPanel_Login);
        MainPanel_Login.setLayout(MainPanel_LoginLayout);
        MainPanel_LoginLayout.setHorizontalGroup(
            MainPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel_LoginLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(MainPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(MainPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_Login_Login)
                    .addGroup(MainPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(JT_UserName_Login)
                        .addComponent(JT_Password_Login, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        MainPanel_LoginLayout.setVerticalGroup(
            MainPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel_LoginLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(MainPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JT_UserName_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(MainPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JT_Password_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JB_Login_Login)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_LoginLayout = new javax.swing.GroupLayout(JD_Login.getContentPane());
        JD_Login.getContentPane().setLayout(JD_LoginLayout);
        JD_LoginLayout.setHorizontalGroup(
            JD_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_LoginLayout.setVerticalGroup(
            JD_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel7.setText("Registrar");

        jLabel13.setText("Nombre: ");

        jLabel14.setText("Apellido: ");

        jLabel15.setText("Numero Telefono:");

        jLabel16.setText("Ingrese su Username:");

        jLabel17.setText("Ingrese su password: ");

        jLabel18.setText("Wifi Quality: ");

        JSpinner_WifiQuality_Registrar.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        JB_Registrar.setText("Registrar");
        JB_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_RegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_Registrar)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JT_Password_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JSpinner_WifiQuality_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel15))
                                    .addGap(37, 37, 37))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(14, 14, 14)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JT_Usuario_Registrar)
                                .addComponent(JT_Nombre_Registrar)
                                .addComponent(JT_Apellido_Registrar)
                                .addComponent(JT_Telefono_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(JT_Nombre_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(JT_Apellido_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(JT_Telefono_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(JT_Usuario_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(JT_Password_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(JSpinner_WifiQuality_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_Registrar)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_RegistrarLayout = new javax.swing.GroupLayout(JD_Registrar.getContentPane());
        JD_Registrar.getContentPane().setLayout(JD_RegistrarLayout);
        JD_RegistrarLayout.setHorizontalGroup(
            JD_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_RegistrarLayout.setVerticalGroup(
            JD_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JMI_AcceptFriend.setText("Accept Friend Request");
        JMI_AcceptFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_AcceptFriendActionPerformed(evt);
            }
        });
        FriendRequestMenu.add(JMI_AcceptFriend);

        JMI_DenyFriend.setText("Deny Friend Request");
        FriendRequestMenu.add(JMI_DenyFriend);

        JMI_SendMessage.setText("jMenuItem1");
        JMI_SendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_SendMessageActionPerformed(evt);
            }
        });
        MessageMenu.add(JMI_SendMessage);

        TextArea_Chat.setColumns(20);
        TextArea_Chat.setRows(5);
        jScrollPane3.setViewportView(TextArea_Chat);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel19.setText("Chat");

        javax.swing.GroupLayout MainPanel_ListChatLayout = new javax.swing.GroupLayout(MainPanel_ListChat);
        MainPanel_ListChat.setLayout(MainPanel_ListChatLayout);
        MainPanel_ListChatLayout.setHorizontalGroup(
            MainPanel_ListChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel_ListChatLayout.createSequentialGroup()
                .addGroup(MainPanel_ListChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanel_ListChatLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanel_ListChatLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        MainPanel_ListChatLayout.setVerticalGroup(
            MainPanel_ListChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel_ListChatLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_ShowMessageLayout = new javax.swing.GroupLayout(JD_ShowMessage.getContentPane());
        JD_ShowMessage.getContentPane().setLayout(JD_ShowMessageLayout);
        JD_ShowMessageLayout.setHorizontalGroup(
            JD_ShowMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel_ListChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_ShowMessageLayout.setVerticalGroup(
            JD_ShowMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel_ListChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JMI_SeeChat.setText("See Chat");
        SeeMessageMenu.add(JMI_SeeChat);

        jLabel20.setText("Mensaje");

        jLabel21.setText("Contenido");

        TextArea_Mensaje.setColumns(20);
        TextArea_Mensaje.setRows(5);
        jScrollPane4.setViewportView(TextArea_Mensaje);

        jButton1.setText("Send");

        javax.swing.GroupLayout MainPanel_MensajeLayout = new javax.swing.GroupLayout(MainPanel_Mensaje);
        MainPanel_Mensaje.setLayout(MainPanel_MensajeLayout);
        MainPanel_MensajeLayout.setHorizontalGroup(
            MainPanel_MensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel_MensajeLayout.createSequentialGroup()
                .addGroup(MainPanel_MensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanel_MensajeLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanel_MensajeLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainPanel_MensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        MainPanel_MensajeLayout.setVerticalGroup(
            MainPanel_MensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel_MensajeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel20)
                .addGap(42, 42, 42)
                .addGroup(MainPanel_MensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_MensajeLayout = new javax.swing.GroupLayout(JD_Mensaje.getContentPane());
        JD_Mensaje.getContentPane().setLayout(JD_MensajeLayout);
        JD_MensajeLayout.setHorizontalGroup(
            JD_MensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel_Mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_MensajeLayout.setVerticalGroup(
            JD_MensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel_Mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Ingrese su Username:");

        jLabel5.setText("Ingrese su password: ");

        jLabel6.setText("Wifi Quality: ");

        JSpinner_WifiQuality.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        JB_CreateUsuario.setText("Create");
        JB_CreateUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CreateUsuarioActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre: ");

        jLabel11.setText("Apellido: ");

        jLabel12.setText("Numero Telefono:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_CreateUsuario)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JT_Password_Create, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JSpinner_WifiQuality, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12))
                                    .addGap(37, 37, 37))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(14, 14, 14)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JT_Usuario_Create)
                                .addComponent(JT_Nombre_Create)
                                .addComponent(JT_Apellido_Create)
                                .addComponent(JT_Telefono_Create)))))
                .addContainerGap(420, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JT_Nombre_Create, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(JT_Apellido_Create, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(JT_Telefono_Create, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JT_Usuario_Create, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JT_Password_Create, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JSpinner_WifiQuality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_CreateUsuario)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Create/Remove", jPanel1);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Receptores");
        JTree_Receptores.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        JTree_Receptores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTree_ReceptoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JTree_Receptores);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(501, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("JTree", jPanel4);

        jLabel10.setText("Enter group name: ");

        JB_CreateGroup.setText("Create Group");
        JB_CreateGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CreateGroupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_CreateGroup)
                    .addComponent(JT_GroupName, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(JT_GroupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JB_CreateGroup)
                .addContainerGap(319, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Create Groups", jPanel6);

        JList_Friends.setModel(new DefaultListModel());
        JList_Friends.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JList_FriendsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JList_Friends);

        JB_ListFriends.setText("List Friends");
        JB_ListFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ListFriendsActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Send Friend Requests"));
        jPanel5.setToolTipText("");

        JB_SendSolicitud.setText("Send");
        JB_SendSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SendSolicitudActionPerformed(evt);
            }
        });

        jLabel8.setText("Ingrese el Username del amigo al que quieres mandar el solicitud");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT_UserToSend, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_SendSolicitud))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JT_UserToSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JB_SendSolicitud)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel9.setText("Friend Requests Pending");

        JB_ListRequests.setText("List Friend Requests");
        JB_ListRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ListRequestsActionPerformed(evt);
            }
        });

        CB_Requests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CB_RequestsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_ListFriends)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JB_ListRequests))
                    .addComponent(CB_Requests, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JB_ListFriends)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(JB_ListRequests))
                        .addGap(5, 5, 5)
                        .addComponent(CB_Requests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Friends", jPanel2);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jMenu1.setText("Home");

        JMI_Login.setText("Login");
        JMI_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_LoginActionPerformed(evt);
            }
        });
        jMenu1.add(JMI_Login);

        JMI_Registrar.setText("Registrar");
        jMenu1.add(JMI_Registrar);

        MainMenuBar.add(jMenu1);

        jMenu2.setText("Edit");
        MainMenuBar.add(jMenu2);

        setJMenuBar(MainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMI_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_LoginActionPerformed
        // TODO add your handling code here:
        JD_Login.setModal(true);
        JD_Login.pack();
        JD_Login.setLocationRelativeTo(this);
        JD_Login.setVisible(true);
    }//GEN-LAST:event_JMI_LoginActionPerformed

    private void JB_CreateUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CreateUsuarioActionPerformed
        // TODO add your handling code here:
        //String username, String password, int wifiquality
        int quality = Integer.parseInt(this.JSpinner_WifiQuality.getValue().toString());
        Usuarios x = new Usuarios(this.JT_Usuario_Create.getText(), this.JT_Password_Create.getText(), quality, this.JT_Nombre_Create.getText(),
                this.JT_Apellido_Create.getText(), this.JT_Telefono_Create.getText());
        archivo = new File("./Usuarios");
        LoadFile();
        listaUsuarios.add(x);
        writeFile();

    }//GEN-LAST:event_JB_CreateUsuarioActionPerformed

    private void JB_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_RegistrarActionPerformed
        // TODO add your handling code here:
        int quality = Integer.parseInt(this.JSpinner_WifiQuality_Registrar.getValue().toString());
        Usuarios x = new Usuarios(this.JT_Usuario_Registrar.getText(), this.JT_Password_Registrar.getText(), quality, this.JT_Nombre_Registrar.getText(),
                this.JT_Apellido_Registrar.getText(), this.JT_Telefono_Registrar.getText());
        archivo = new File("./Usuarios");
        LoadFile();
        listaUsuarios.add(x);
        writeFile();
    }//GEN-LAST:event_JB_RegistrarActionPerformed

    private void JB_ListFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ListFriendsActionPerformed
        // TODO add your handling code here:
        archivo = new File("./Usuarios");
        LoadFile();
        numberLoggedIn = 0;
        for (int i = 0; i < listaUsuarios.size(); i++) {
            listaUsuarios.get(i).getUsername().equals(loggedIn);
            numberLoggedIn = i;
        }
        DefaultListModel modelo
                = (DefaultListModel) JList_Friends.getModel();
        for (int i = 0; i < listaUsuarios.get(numberLoggedIn).getListamigos().size(); i++) {
            modelo.addElement(listaUsuarios.get(numberLoggedIn).getListamigos().get(i));
        }
        JList_Friends.setModel(modelo);
    }//GEN-LAST:event_JB_ListFriendsActionPerformed

    private void JB_Login_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Login_LoginActionPerformed
        // TODO add your handling code here:
        archivo = new File("./Usuarios");
        LoadFile();
        for (int i = 0; i < listaUsuarios.size(); i++) {
            if (listaUsuarios.get(i).getUsername().equals(JT_UserName_Login.getText())
                    && listaUsuarios.get(i).getPassword().equals(JT_Password_Login.getText())) {
                loggedIn = JT_UserName_Login.getText();
            }

        }
    }//GEN-LAST:event_JB_Login_LoginActionPerformed

    private void JB_SendSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SendSolicitudActionPerformed
        // TODO add your handling code here:
        //String sender, Usuarios user
        String ToSolicitud = this.JT_UserToSend.getText();
        archivo = new File("./Usuarios");
        LoadFile();
        //Solicitud x = new Solicitud(loggedIn,listaUsuarios.get(numberLoggedIn));
        for (int i = 0; i < listaUsuarios.size(); i++) {
            if (listaUsuarios.get(i).getUsername().equals(ToSolicitud)) {
                listaUsuarios.get(i).setListsolicitudes(listaUsuarios.get(numberLoggedIn));
            }

        }

    }//GEN-LAST:event_JB_SendSolicitudActionPerformed

    private void JB_ListRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ListRequestsActionPerformed
        // TODO add your handling code here:
        archivo = new File("./Usuarios");
        LoadFile();
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) CB_Requests.getModel();
        for (int i = 0; i < listaUsuarios.get(numberLoggedIn).getListsolicitudes().size(); i++) {
            modelo.addElement(listaUsuarios.get(numberLoggedIn).getListsolicitudes().get(i));
        }
    }//GEN-LAST:event_JB_ListRequestsActionPerformed

    private void JMI_AcceptFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_AcceptFriendActionPerformed
        // TODO add your handling code here:
        //int JListRequest = JList_Requests.getSelectedIndex();
        archivo = new File("./Usuarios");
//        for (int i = 0; i < listaUsuarios.size(); i++) {
//            listaUsuarios.get(i).setListamigos()
//        }
        listaUsuarios.get(numberLoggedIn).setListamigos((Usuarios) CB_Requests.getSelectedItem());
    }//GEN-LAST:event_JMI_AcceptFriendActionPerformed

    private void CB_RequestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CB_RequestsMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            FriendRequestMenu.show(evt.getComponent(),
                    evt.getX(), evt.getY());

        }
    }//GEN-LAST:event_CB_RequestsMouseClicked

    private void JList_FriendsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JList_FriendsMouseClicked
        // TODO add your handling code here:
        if (JList_Friends.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                MessageMenu.show(evt.getComponent(),
                        evt.getX(), evt.getY());

            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "No hay persona seleccionada");
        }
    }//GEN-LAST:event_JList_FriendsMouseClicked

    private void JMI_SendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_SendMessageActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel modeloARBOL
                = (DefaultTreeModel) JTree_Receptores.getModel();
        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) modeloARBOL.getRoot();
        DefaultListModel modeloLISTA
                = (DefaultListModel) JList_Friends.getModel();
        int wifiquality;
        String username, password, nombre, apellido, numeroCel;
        username
                = ((Usuarios) modeloLISTA.get(
                        JList_Friends.getSelectedIndex())).getUsername();
        password
                = ((Usuarios) modeloLISTA.get(
                        JList_Friends.getSelectedIndex())).getPassword();
        nombre
                = ((Usuarios) modeloLISTA.get(
                        JList_Friends.getSelectedIndex())).getNombre();
        apellido
                = ((Usuarios) modeloLISTA.get(
                        JList_Friends.getSelectedIndex())).getApellido();
        numeroCel
                = ((Usuarios) modeloLISTA.get(
                        JList_Friends.getSelectedIndex())).getNumeroCel();
        wifiquality
                = ((Usuarios) modeloLISTA.get(
                        JList_Friends.getSelectedIndex())).getWifiquality();
        //String username, String password, int wifiquality, String nombre, String apellido, String numeroCel
        int centinela = -1;
        for (int i = 0; i < raiz.getChildCount(); i++) {
            if (raiz.getChildAt(i).toString().
                    equals(username)) {
                DefaultMutableTreeNode p
                        = new DefaultMutableTreeNode(
                                new Usuarios(username, password, wifiquality, nombre, apellido, numeroCel)
                        );
                ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                centinela = 1;
            } //fin if
        } //fin for  

        if (centinela == -1) {
            DefaultMutableTreeNode n
                    = new DefaultMutableTreeNode(username);
            DefaultMutableTreeNode p
                    = new DefaultMutableTreeNode(
                            new Usuarios(username, password, wifiquality, nombre, apellido, numeroCel)
                    );
            n.add(p);
            raiz.add(n);
        }  // fin if          
        modeloARBOL.reload();
        archivo = new File("./Usuarios");
        LoadFile();
        Mensaje x = new Mensaje();
        

    }//GEN-LAST:event_JMI_SendMessageActionPerformed

    private void JB_CreateGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CreateGroupActionPerformed
        // TODO add your handling code here:
        archivo = new File("./Usuarios");
        LoadFile();
        Grupo x = new Grupo(this.JT_GroupName.getText(),listaUsuarios.get(numberLoggedIn));
        
    }//GEN-LAST:event_JB_CreateGroupActionPerformed

    private void JTree_ReceptoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTree_ReceptoresMouseClicked
        // TODO add your handling code here:
         if (evt.isMetaDown()) {
            //seleccionar un nodo con click derecho
            int row = JTree_Receptores.getClosestRowForLocation(
                    evt.getX(), evt.getY());
            JTree_Receptores.setSelectionRow(row);
            Object v1
                    = JTree_Receptores.getSelectionPath().
                    getLastPathComponent();
//            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof Grupo) {
                grupo_seleccionada
                        = (Grupo) nodo_seleccionado.
                        getUserObject();
                SeeMessageMenu.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
            if (nodo_seleccionado.getUserObject() instanceof Usuarios) {
                grupo_seleccionada
                        = (Grupo) nodo_seleccionado.
                        getUserObject();
                SeeMessageMenu.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }

        }
    }//GEN-LAST:event_JTree_ReceptoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainExamenLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainExamenLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainExamenLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainExamenLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainExamenLab().setVisible(true);
            }
        });
    }

    public void writeFile() {
        FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        try {
            fw = new FileOutputStream(archivo);
            bw = new ObjectOutputStream(fw);
            for (Usuarios t : listaUsuarios) {
                bw.writeObject(t);
            }
            //bw.writeObject(x);
            bw.flush();
        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            try {
                bw.close();
                fw.close();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }

    public void LoadFile() {
        try {
            listaUsuarios = new ArrayList();
            Usuarios temp;
            if (archivo.exists()) {
                FileInputStream entrada
                        = new FileInputStream(archivo);
                ObjectInputStream objeto
                        = new ObjectInputStream(entrada);
                try {
                    while ((temp = (Usuarios) objeto.readObject()) != null) {
                        listaUsuarios.add(temp);
                    }
                } catch (EOFException e) {
                    //encontro el final del archivo
                    //e.printStackTrace();
                }
                objeto.close();
                entrada.close();
            } //fin if           
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    Grupo grupo_seleccionada;
    DefaultMutableTreeNode nodo_seleccionado;
    int numberLoggedIn = 0;
    String loggedIn = "";
    File archivo = null;
    ArrayList<Usuarios> listaUsuarios = new ArrayList();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_Requests;
    private javax.swing.JPopupMenu FriendRequestMenu;
    private javax.swing.JButton JB_CreateGroup;
    private javax.swing.JButton JB_CreateUsuario;
    private javax.swing.JButton JB_ListFriends;
    private javax.swing.JButton JB_ListRequests;
    private javax.swing.JButton JB_Login_Login;
    private javax.swing.JButton JB_Registrar;
    private javax.swing.JButton JB_SendSolicitud;
    private javax.swing.JDialog JD_Login;
    private javax.swing.JDialog JD_Mensaje;
    private javax.swing.JDialog JD_Registrar;
    private javax.swing.JDialog JD_ShowMessage;
    private javax.swing.JList<String> JList_Friends;
    private javax.swing.JMenuItem JMI_AcceptFriend;
    private javax.swing.JMenuItem JMI_DenyFriend;
    private javax.swing.JMenuItem JMI_Login;
    private javax.swing.JMenuItem JMI_Registrar;
    private javax.swing.JMenuItem JMI_SeeChat;
    private javax.swing.JMenuItem JMI_SendMessage;
    private javax.swing.JSpinner JSpinner_WifiQuality;
    private javax.swing.JSpinner JSpinner_WifiQuality_Registrar;
    private javax.swing.JTextField JT_Apellido_Create;
    private javax.swing.JTextField JT_Apellido_Registrar;
    private javax.swing.JTextField JT_GroupName;
    private javax.swing.JTextField JT_Nombre_Create;
    private javax.swing.JTextField JT_Nombre_Registrar;
    private javax.swing.JTextField JT_Password_Create;
    private javax.swing.JTextField JT_Password_Login;
    private javax.swing.JTextField JT_Password_Registrar;
    private javax.swing.JTextField JT_Telefono_Create;
    private javax.swing.JTextField JT_Telefono_Registrar;
    private javax.swing.JTextField JT_UserName_Login;
    private javax.swing.JTextField JT_UserToSend;
    private javax.swing.JTextField JT_Usuario_Create;
    private javax.swing.JTextField JT_Usuario_Registrar;
    private javax.swing.JTree JTree_Receptores;
    private javax.swing.JMenuBar MainMenuBar;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel MainPanel_ListChat;
    private javax.swing.JPanel MainPanel_Login;
    private javax.swing.JPanel MainPanel_Mensaje;
    private javax.swing.JPopupMenu MessageMenu;
    private javax.swing.JPopupMenu SeeMessageMenu;
    private javax.swing.JTextArea TextArea_Chat;
    private javax.swing.JTextArea TextArea_Mensaje;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
